### ISSUE TITLE
Readme is missing violations list

### ISSUE THREAD

**Issue by sobolevn** [best-doctor/flake8-annotations-coverage#3]
It is a good practice for `flake8` plugins to list all violations in the readme.
You can find a lot of examples here: https://wemake-python-styleguide.readthedocs.io/en/latest/pages/violations/index.html

**Comment by Melevir** [comment]
This is still legit.

**Comment by lowitea** [comment]
Hi @Melevir !
I have made PR #9 
Could you please check it
