### ISSUE TITLE
Add "--ignore-untyped" option

### ISSUE THREAD

**Issue by sobolevn** [best-doctor/flake8-annotations-coverage#7]
I have a file with several `django` views, which are not typed at all.
This plugin raises a violation for it.

So, my feature request is to create "--ignore-untyped" option that will suppress warning for files that are not typed at all.

**Comment by Melevir** [comment]
Consider annotating these files or using https://github.com/snoack/flake8-per-file-ignores (build in flake8 3.7.5).
